on:
  workflow_dispatch

name: Manual Release
jobs:
  manual_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run NPM CI
        run: npm ci

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Package Extension (VSIX)
        uses: lannonbr/vsce-action@master
        with:
          args: "package"

      - name: Zip VSIX
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: panorama-css-${{ steps.package-version.outputs.current-version }}.vsix
          filename: 'extension.zip'

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: ${{ steps.package-version.outputs.current-version }}
          body_path: CHANGELOG_CURRENT.md
          draft: true
          prerelease: false
          
      - name: Upload VSIX Zip to Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.zip
          asset_name: extension.zip
          asset_content_type: application/zip

      - name: Publish Release
        uses: eregon/publish-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
